/////////////////////////////////////////////////////////////////////////////
// Name:        atlas.cpp
// Purpose:     
// Author:      
// Modified by: 
// Created:     01/03/2021 13:12:37
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 01/03/2021 13:12:37

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "atlas.h"

////@begin XPM images

////@end XPM images


/*
 * wxFrame type definition
 */

IMPLEMENT_CLASS( wxFrame, wxFrame )


/*
 * wxFrame event table definition
 */

BEGIN_EVENT_TABLE( wxFrame, wxFrame )

////@begin wxFrame event table entries
////@end wxFrame event table entries

END_EVENT_TABLE()


/*
 * wxFrame constructors
 */

wxFrame::wxFrame()
{
    Init();
}

wxFrame::wxFrame( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create( parent, id, caption, pos, size, style );
}


/*
 * wxFrame creator
 */

bool wxFrame::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin wxFrame creation
    SetParent(parent);
    CreateControls();
    Centre();
////@end wxFrame creation
    return true;
}


/*
 * wxFrame destructor
 */

wxFrame::~wxFrame()
{
////@begin wxFrame destruction
////@end wxFrame destruction
}


/*
 * Member initialisation
 */

void wxFrame::Init()
{
////@begin wxFrame member initialisation
////@end wxFrame member initialisation
}


/*
 * Control creation for wxFrame
 */

void wxFrame::CreateControls()
{    
////@begin wxFrame content construction
    // Generated by DialogBlocks, 01/03/2021 13:12:37 (unregistered)

    if (!wxXmlResource::Get()->LoadFrame(this, GetParent(), wxT("ID_WXFRAME")))
        wxLogError(wxT("Missing wxXmlResource::Get()->Load() in OnInit()?"));
////@end wxFrame content construction

    // Create custom windows not generated automatically here.
////@begin wxFrame content initialisation
////@end wxFrame content initialisation
}


/*
 * Should we show tooltips?
 */

bool wxFrame::ShowToolTips()
{
    return true;
}

/*
 * Get bitmap resources
 */

wxBitmap wxFrame::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin wxFrame bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end wxFrame bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon wxFrame::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin wxFrame icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end wxFrame icon retrieval
}
