/////////////////////////////////////////////////////////////////////////////
// Name:        atlas.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     01/03/2021 13:12:37
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 01/03/2021 13:12:37

#ifndef _ATLAS_H_
#define _ATLAS_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/frame.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_WXFRAME 10000
#define SYMBOL_WXFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_WXFRAME_TITLE _("Atlas")
#define SYMBOL_WXFRAME_IDNAME ID_WXFRAME
#define SYMBOL_WXFRAME_SIZE wxSize(400, 300)
#define SYMBOL_WXFRAME_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * wxFrame class declaration
 */

class wxFrame: public wxFrame
{    
    DECLARE_CLASS( wxFrame )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxFrame();
    wxFrame( wxWindow* parent, wxWindowID id = SYMBOL_WXFRAME_IDNAME, const wxString& caption = SYMBOL_WXFRAME_TITLE, const wxPoint& pos = SYMBOL_WXFRAME_POSITION, const wxSize& size = SYMBOL_WXFRAME_SIZE, long style = SYMBOL_WXFRAME_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXFRAME_IDNAME, const wxString& caption = SYMBOL_WXFRAME_TITLE, const wxPoint& pos = SYMBOL_WXFRAME_POSITION, const wxSize& size = SYMBOL_WXFRAME_SIZE, long style = SYMBOL_WXFRAME_STYLE );

    /// Destructor
    ~wxFrame();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxFrame event handler declarations
////@end wxFrame event handler declarations

////@begin wxFrame member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxFrame member variables
////@end wxFrame member variables
};

#endif
    // _ATLAS_H_
