/////////////////////////////////////////////////////////////////////////////
// Name:        home.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     27/02/2021 08:32:57
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 27/02/2021 08:32:57

#ifndef _HOME_H_
#define _HOME_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/frame.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_WXFRAME 10000
#define SYMBOL_WXFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_WXFRAME_TITLE _("Home")
#define SYMBOL_WXFRAME_IDNAME ID_WXFRAME
#define SYMBOL_WXFRAME_SIZE wxSize(400, 300)
#define SYMBOL_WXFRAME_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * wxPanel class declaration
 */

class wxPanel: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( wxPanel )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxPanel();
    wxPanel( wxWindow* parent, wxWindowID id = SYMBOL_WXPANEL_IDNAME, const wxPoint& pos = SYMBOL_WXPANEL_POSITION, const wxSize& size = SYMBOL_WXPANEL_SIZE, long style = SYMBOL_WXPANEL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXPANEL_IDNAME, const wxPoint& pos = SYMBOL_WXPANEL_POSITION, const wxSize& size = SYMBOL_WXPANEL_SIZE, long style = SYMBOL_WXPANEL_STYLE );

    /// Destructor
    ~wxPanel();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxPanel event handler declarations

////@end wxPanel event handler declarations

////@begin wxPanel member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxPanel member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxPanel member variables
////@end wxPanel member variables
};

/*!
 * wxFrame class declaration
 */

class wxFrame: public wxFrame
{    
    DECLARE_CLASS( wxFrame )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxFrame();
    wxFrame( wxWindow* parent, wxWindowID id = SYMBOL_WXFRAME_IDNAME, const wxString& caption = SYMBOL_WXFRAME_TITLE, const wxPoint& pos = SYMBOL_WXFRAME_POSITION, const wxSize& size = SYMBOL_WXFRAME_SIZE, long style = SYMBOL_WXFRAME_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXFRAME_IDNAME, const wxString& caption = SYMBOL_WXFRAME_TITLE, const wxPoint& pos = SYMBOL_WXFRAME_POSITION, const wxSize& size = SYMBOL_WXFRAME_SIZE, long style = SYMBOL_WXFRAME_STYLE );

    /// Destructor
    ~wxFrame();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxFrame event handler declarations

////@end wxFrame event handler declarations

////@begin wxFrame member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxFrame member variables
////@end wxFrame member variables
};

#endif
    // _HOME_H_
